apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  name: liferay-aws-platform-infrastructure.aws.liferay.com
spec:
  compositeTypeRef:
    apiVersion: aws.liferay.com/v1alpha1
    kind: LiferayDependencies
  mode: Pipeline
  pipeline:
    - step: liferay-infrastructure
      functionRef:
        name: function-go-templating
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{`
            {{- $accountId := `}}{{ .Values.aws.accountId | quote }}{{` -}}
            {{- $liferayServiceAccountRoleName := `}}{{ .Values.liferayServiceAccountRoleName | quote }}{{` -}}
            {{- $nodesSecurityGroupId := `}}{{ .Values.aws.nodesSecurityGroupId | quote }}{{` -}}
            {{- $vpcId := `}}{{ .Values.aws.vpcId | quote }}{{` -}}
            {{- $privateSubnetIds := `}}{{ .Values.aws.privateSubnetIds | quote }}{{` -}}

            {{- $privateSubnetIdsList := $privateSubnetIds | fromJson -}}
            {{- $xr := .observed.composite.resource -}}

            {{- $databaseSpec := $xr.spec.database }}
            {{- $databaseSlots := dict "blue" $databaseSpec.blue "green" $databaseSpec.green -}}

            {{- range $slot, $spec := $databaseSlots }}
            ---
            apiVersion: rds.aws.m.upbound.io/v1beta1
            kind: Instance
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-database-{{ $slot }}
                gotemplating.fn.crossplane.io/composition-resource-name: database-{{ $slot }}
              labels:
                app: liferay
                component: database
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-database-{{ $slot }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                allocatedStorage: {{ $spec.storageGB }}
                autoGeneratePassword: true
                dbSubnetGroupNameSelector:
                  matchLabels:
                    app: liferay
                    component: database-subnet-group
                    slot: {{ $slot }}
                engine: postgres
                engineVersion: "16.11"
                identifier: {{ $xr.metadata.name }}-database-{{ $slot }}
                instanceClass: {{ $spec.instanceClass }}
                passwordSecretRef:
                  key: password
                  name: liferay-database-{{ $slot }}-password
                region: {{ $spec.region }}
                skipFinalSnapshot: true
                username: {{ $spec.username }}
                vpcSecurityGroupIdSelector:
                  matchLabels:
                    app: liferay
                    component: database-security-group
                    slot: {{ $slot }}
                tags:
                  Active: {{ printf "%t" (eq $slot $databaseSpec.activeSlot) }}
                  Backup: true
                  Name: {{ $xr.metadata.name }}-database-{{ $slot }}
              writeConnectionSecretToRef:
                name: liferay-database-{{ $slot }}-credentials
            ---
            apiVersion: ec2.aws.m.upbound.io/v1beta1
            kind: SecurityGroup
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: database-security-group-{{ $slot }}
              labels:
                app: liferay
                component: database-security-group
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-database-security-group-{{ $slot }}
            spec:
              forProvider:
                name: {{ $xr.metadata.name }}-database-security-group-{{ $slot }}
                region: {{ $spec.region }}
                tags:
                  Name: {{ $xr.metadata.name }}-database-security-group-{{ $slot }}
                vpcId: {{ $vpcId }}
            ---
            apiVersion: ec2.aws.m.upbound.io/v1beta1
            kind: SecurityGroupIngressRule
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: database-security-group-ingress-{{ $slot }}
              labels:
                app: liferay
                component: database-security-group-ingress
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-database-security-group-ingress-{{ $slot }}
            spec:
              forProvider:
                fromPort: 5432
                ipProtocol: tcp
                toPort: 5432
                referencedSecurityGroupId: {{ $nodesSecurityGroupId }}
                region: {{ $spec.region }}
                securityGroupIdSelector:
                  matchLabels:
                    app: liferay
                    component: database-security-group
                    slot: {{ $slot }}
            ---
            apiVersion: rds.aws.m.upbound.io/v1beta1
            kind: SubnetGroup
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-database-subnet-group-{{ $slot }}
                gotemplating.fn.crossplane.io/composition-resource-name: database-subnet-group-{{ $slot }}
              labels:
                app: liferay
                component: database-subnet-group
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-database-subnet-group-{{ $slot }}
            spec:
              forProvider:
                region: {{ $spec.region }}
                subnetIds: {{ $privateSubnetIdsList | toJson }}
                tags:
                  Name: {{ $xr.metadata.name }}-database-{{ $slot }}-subnets
            {{- end }}

            {{- $storageSpec := $xr.spec.storage }}
            {{- $storageSlots := dict "blue" $storageSpec.blue "green" $storageSpec.green -}}

            {{- range $slot, $spec := $storageSlots }}
            ---
            apiVersion: s3.aws.m.upbound.io/v1beta1
            kind: Bucket
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-storage-{{ $slot }}
                gotemplating.fn.crossplane.io/composition-resource-name: storage-{{ $slot }}
              labels:
                app: liferay
                component: storage
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-storage-{{ $slot }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                region: {{ $spec.region }}
                tags:
                  Active: {{ printf "%t" (eq $slot $storageSpec.activeSlot) }}
                  Backup: true
                  Name: {{ $xr.metadata.name }}-storage-{{ $slot }}
            ---
            apiVersion: s3.aws.m.upbound.io/v1beta1
            kind: BucketVersioning
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-storage-versioning-{{ $slot }}
                gotemplating.fn.crossplane.io/composition-resource-name: storage-versioning-{{ $slot }}
              labels:
                app: liferay
                component: storage-versioning
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-storage-versioning-{{ $slot }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                bucketSelector:
                  matchLabels:
                    app: liferay
                    component: storage
                    slot: {{ $slot }}
                  namespace: {{ $xr.metadata.namespace }}
                region: {{ $spec.region }}
                versioningConfiguration:
                  status: Enabled
            ---
            apiVersion: iam.aws.m.upbound.io/v1beta1
            kind: Policy
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-storage-policy-{{ $slot }}
                gotemplating.fn.crossplane.io/composition-resource-name: storage-policy-{{ $slot }}
              labels:
                app: liferay
                component: storage-policy
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-storage-policy-{{ $slot }}
            spec:
              forProvider:
                policy: |
                  {
                    "Statement": [
                      {
                        "Action": [
                          "s3:DeleteObject",
                          "s3:GetObject",
                          "s3:ListBucket",
                          "s3:PutObject"
                        ],
                        "Effect": "Allow",
                        "Resource": [
                          "arn:aws:s3:::{{ $xr.metadata.name }}-storage-{{ $slot }}",
                          "arn:aws:s3:::{{ $xr.metadata.name }}-storage-{{ $slot }}/*"
                        ]
                      }
                    ]
                    "Version": "2012-10-17"
                  }
            ---
            apiVersion: iam.aws.m.upbound.io/v1beta1
            kind: RolePolicyAttachment
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-storage-policy-attachment-{{ $slot }}
                gotemplating.fn.crossplane.io/composition-resource-name: storage-policy-attachment-{{ $slot }}
              labels:
                app: liferay
                component: storage-policy-attachment
                slot: {{ $slot }}
              name: {{ $xr.metadata.name }}-storage-policy-attachment-{{ $slot }}
            spec:
              forProvider:
                policyArnSelector:
                  matchLabels:
                    app: liferay
                    component: storage-policy
                    slot: {{ $slot }}
                role: {{ $liferayServiceAccountRoleName }}
            {{- end }}

            {{- $searchSpec := $xr.spec.search }}
            {{- $searchName := printf "%.20s-search" $xr.metadata.name -}}

            ---
            apiVersion: opensearch.aws.m.upbound.io/v1beta1
            kind: Domain
            metadata:
              annotations:
                crossplane.io/external-name: {{ $searchName }}
                gotemplating.fn.crossplane.io/composition-resource-name: search
              labels:
                app: liferay
                component: search
              name: {{ $searchName }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                domainName: {{ $searchName }}
                region: {{ $searchSpec.region }}
                engineVersion: {{ $searchSpec.engineVersion }}
                clusterConfig:
                  instanceCount: {{ $searchSpec.instanceCount }}
                  instanceType: {{ $searchSpec.instanceType }}
                  zoneAwarenessEnabled: true
                  zoneAwarenessConfig:
                    availabilityZoneCount: 2
                ebsOptions:
                  ebsEnabled: true
                  volumeSize: 20
                  volumeType: gp3
                advancedSecurityOptions:
                  enabled: true
                  internalUserDatabaseEnabled: true
                  masterUserOptions:
                    masterUserName: {{ $searchSpec.username }}
                    masterUserPasswordSecretRef:
                      name: liferay-search-password
                      key: password
                encryptAtRest:
                  enabled: true
                nodeToNodeEncryption:
                  enabled: true
                domainEndpointOptions:
                  enforceHttps: true
                  tlsSecurityPolicy: Policy-Min-TLS-1-2-2019-07
                tags:
                  Name: {{ $searchName }}
                vpcOptions:
                  securityGroupIdSelector:
                    matchLabels:
                      app: liferay
                      component: search-security-group
                  subnetIds: {{ slice $privateSubnetIdsList 0 2 | toJson }}
              writeConnectionSecretToRef:
                name: liferay-search-credentials
            ---
            apiVersion: opensearch.aws.m.upbound.io/v1beta1
            kind: DomainPolicy
            metadata:
              annotations:
                crossplane.io/external-name: {{ $searchName }}-policy
                gotemplating.fn.crossplane.io/composition-resource-name: search-policy
              labels:
                app: liferay
                component: search-policy
              name: {{ $searchName }}-policy
            spec:
              forProvider:
                domainNameSelector:
                  matchLabels:
                    app: liferay
                    component: search
                region: {{ $searchSpec.region }}
                accessPolicies: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Action": "es:*",
                        "Effect": "Allow",
                        "Principal": {
                          "AWS": "arn:aws:iam::{{ $accountId }}:role/{{ $liferayServiceAccountRoleName }}"
                        },
                        "Resource": "arn:aws:es:{{ $searchSpec.region }}:{{ $accountId }}:domain/{{ $searchName }}/*"
                      }
                    ]
                  }
            ---
            apiVersion: ec2.aws.m.upbound.io/v1beta1
            kind: SecurityGroup
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: search-security-group
              labels:
                app: liferay
                component: search-security-group
              name: {{ $searchName }}-security-group
            spec:
              forProvider:
                name: {{ $searchName }}-security-group
                region: {{ $searchSpec.region }}
                tags:
                  Name: {{ $searchName }}-security-group
                vpcId: {{ $vpcId }}
            ---
            apiVersion: ec2.aws.m.upbound.io/v1beta1
            kind: SecurityGroupIngressRule
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: search-security-group-ingress
              labels:
                app: liferay
                component: search-security-group-ingress
              name: {{ $searchName }}-security-group-ingress
            spec:
              forProvider:
                fromPort: 443
                ipProtocol: tcp
                toPort: 443
                referencedSecurityGroupId: {{ $nodesSecurityGroupId }}
                region: {{ $searchSpec.region }}
                securityGroupIdSelector:
                  matchLabels:
                    app: liferay
                    component: search-security-group
            `}}
    - step: managed-service-details-secret
      functionRef:
        name: function-go-templating
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{`
            {{- $xr := .observed.composite.resource -}}
            {{- $databaseResourceName := printf "database-%s" $xr.spec.database.activeSlot -}}
            {{- $searchResourceName := "search" -}}
            {{- $storageResourceName := printf "storage-%s" $xr.spec.storage.activeSlot -}}

            {{- $database := dict -}}
            {{- $search := dict -}}
            {{- $storage := dict -}}

            {{- if .observed.resources -}}
              {{- $database = index .observed.resources $databaseResourceName -}}
              {{- $search = index .observed.resources $searchResourceName -}}
              {{- $storage = index .observed.resources $storageResourceName -}}
            {{- end -}}

            {{- $databaseAddress := "" -}}
            {{- if kindIs "map" $database -}}
              {{- with $database }}
                {{- with .resource }}
                  {{- with .status }}
                    {{- with .atProvider }}
                      {{- $databaseAddress = .address -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- $searchEndpoint := "" -}}
            {{- if kindIs "map" $search -}}
              {{- with $search }}
                {{- with .resource }}
                  {{- with .status }}
                    {{- with .atProvider }}
                      {{- $searchEndpoint = .endpoint -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- $storageName := "" -}}
            {{- if kindIs "map" $storage -}}
              {{- with $storage }}
                {{- with .resource }}
                  {{- with .metadata }}
                    {{- with .annotations }}
                      {{- $storageName = index . "crossplane.io/external-name" -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- if and $database.connectionDetails $databaseAddress $searchEndpoint $storageName }}
            ---
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-managed-service-details-secret
                gotemplating.fn.crossplane.io/composition-resource-name: managed-service-details-secret
              labels:
                app: liferay
                component: managed-service-details-secret
              name: {{ $xr.metadata.name }}-managed-service-details-secret
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: managed-service-details
                    namespace: {{ $xr.metadata.namespace }}
                  type: Opaque
                  stringData:
                    DATABASE_ENDPOINT: {{ $databaseAddress | toString }}
                    DATABASE_PASSWORD: {{ $database.connectionDetails.password | default "" | toString }}
                    DATABASE_PORT: {{ $database.resource.status.atProvider.port | default 5432 | toString }}
                    DATABASE_USERNAME: {{ $database.resource.spec.forProvider.username | toString }}
                    OPENSEARCH_ENDPOINT: "https://{{ $searchEndpoint }}"
                    OPENSEARCH_PASSWORD: {{ $search.connectionDetails.password | default "" | toString }}
                    OPENSEARCH_USERNAME: {{ $search.resource.spec.username }}
                    S3_BUCKET_ID: {{ $storageName | toString }}
                    S3_BUCKET_REGION: {{ $storage.resource.spec.forProvider.region | toString }}
            {{- end }}
            `}}
    - step: apply-default-tags
      functionRef:
        name: function-tag-manager
      input:
        addTags:
          - tags:
              DeploymentName: {{ .Values.deploymentName }}
            type: FromValue
        apiVersion: tag-manager.fn.crossplane.io/v1beta1
        kind: ManagedTags
    - step: auto-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready