apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  name: liferay-aws-platform-infrastructure.aws.liferay.com
spec:
  compositeTypeRef:
    apiVersion: aws.liferay.com/v1alpha1
    kind: LiferayDependencies
  mode: Pipeline
  pipeline:
    - step: liferay-infrastructure
      functionRef:
        name: function-go-templating
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{`
            {{- $xr := .observed.composite.resource -}}

            {{- $databaseSlots := dict "blue" $xr.spec.database.blue "green" $xr.spec.database.green -}}

            {{- range $databaseSlot, $databaseSpec := $databaseSlots -}}
            apiVersion: rds.aws.m.upbound.io/v1beta1
            kind: Instance
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-database-{{ $databaseSlot }}
                gotemplating.fn.crossplane.io/composition-resource-name: database-{{ $databaseSlot }}
              labels:
                app: liferay
                component: database
                slot: {{ $databaseSlot }}
              name: {{ $xr.metadata.name }}-database-{{ $databaseSlot }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                allocatedStorage: {{ $databaseSpec.storageGB }}
                autoGeneratePassword: true
                engine: postgres
                engineVersion: "16"
                instanceClass: {{ $databaseSpec.instanceClass }}
                passwordSecretRef:
                  key: password
                  name: liferay-database-{{ $databaseSlot }}-password
                region: {{ $databaseSpec.region }}
                skipFinalSnapshot: true
                username: {{ $databaseSpec.username }}
              providerConfigRef:
                kind: ClusterProviderConfig
                name: default
              writeConnectionSecretToRef:
                name: liferay-database-{{ $databaseSlot }}-credentials
            ---
            {{- end }}

            {{- $storageSlots := dict "blue" $xr.spec.storage.blue "green" $xr.spec.storage.green -}}

            {{- range $storageSlot, $storageSpec := $storageSlots -}}
            ---
            apiVersion: s3.aws.m.upbound.io/v1beta1
            kind: Bucket
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-storage-{{ $storageSlot }}
                gotemplating.fn.crossplane.io/composition-resource-name: storage-{{ $storageSlot }}
              labels:
                app: liferay
                component: storage
                slot: {{ $storageSlot }}
              name: {{ $xr.metadata.name }}-storage-{{ $storageSlot }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                region: {{ $storageSpec.region }}
            ---
            apiVersion: s3.aws.m.upbound.io/v1beta1
            kind: BucketVersioning
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-storage-versioning-{{ $storageSlot }}
                gotemplating.fn.crossplane.io/composition-resource-name: storage-versioning-{{ $storageSlot }}
              labels:
                app: liferay
                component: storage
                slot: {{ $storageSlot }}
              name: {{ $xr.metadata.name }}-storage-versioning-{{ $storageSlot }}
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                bucketSelector:
                  matchLabels:
                    app: liferay
                    component: storage
                    slot: {{ $storageSlot }}
                  namespace: {{ $xr.metadata.namespace }}
                region: {{ $storageSpec.region }}
                versioningConfiguration:
                  status: Enabled
            {{- end }}
            `}}
    - step: managed-service-details-secret
      functionRef:
        name: function-go-templating
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{`
            {{- $xr := .observed.composite.resource -}}
            {{- $databaseResourceName := printf "database-%s" $xr.spec.database.activeSlot -}}
            {{- $storageResourceName := printf "storage-%s" $xr.spec.storage.activeSlot -}}

            {{- $database := dict -}}
            {{- $storage := dict -}}

            {{- if .observed.resources -}}
              {{- $database = index .observed.resources $databaseResourceName -}}
              {{- $storage = index .observed.resources $storageResourceName -}}
            {{- end -}}

            {{- $databaseAddress := "" -}}
            {{- if kindIs "map" $database -}}
              {{- with $database }}
                {{- with .resource }}
                  {{- with .status }}
                    {{- with .atProvider }}
                      {{- $databaseAddress = .address -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- $storageName := "" -}}
            {{- if kindIs "map" $storage -}}
              {{- with $storage }}
                {{- with .resource }}
                  {{- with .metadata }}
                    {{- with .annotations }}
                      {{- $storageName = index . "crossplane.io/external-name" -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- if and $databaseAddress $storageName $database.connectionDetails }}
            ---
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-managed-service-details-secret
                gotemplating.fn.crossplane.io/composition-resource-name: managed-service-details-secret
              name: {{ $xr.metadata.name }}-managed-service-details-secret
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: managed-service-details
                    namespace: {{ $xr.metadata.namespace }}
                  type: Opaque
                  stringData:
                    DATABASE_ENDPOINT: {{ $databaseAddress | toString }}
                    DATABASE_PASSWORD: {{ $database.connectionDetails.password | default "" | toString }}
                    DATABASE_PORT: "{{ $database.resource.status.atProvider.port | default 5432 }}"
                    DATABASE_USERNAME: {{ $database.resource.spec.forProvider.username | toString }}
                    OPENSEARCH_ENDPOINT: ""
                    OPENSEARCH_PASSWORD: ""
                    OPENSEARCH_USERNAME: ""
                    S3_BUCKET_ID: {{ $storageName | toString }}
                    S3_BUCKET_REGION: {{ $storage.resource.spec.forProvider.region | toString }}
            {{- end }}
            `}}
