{{- $crossplaneNamespace := .Values.crossplaneNamespace | default "crossplane-system" -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
  name: crossplane-provider-kubernetes-liferay-manager
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/sync-wave: "-40"
  name: crossplane-provider-kubernetes-liferay-binding
subjects:
- kind: ServiceAccount
  name: provider-kubernetes
  namespace: {{ $crossplaneNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-provider-kubernetes-liferay-manager
