{{- if .Values.enabled -}}
apiVersion: aws.liferay.com/v1alpha1
kind: LiferayDependencies
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-10" | quote }}
  name: {{ include "liferay-aws-infrastructure.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  activeSlot: {{ .Values.activeSlot | quote }}
  blue:
    database:
      instanceClass: {{ .Values.blue.database.instanceClass | quote }}
      masterUsername: {{ .Values.blue.database.masterUsername | quote }}
      region: {{ .Values.blue.database.region | quote }}
      storageGB: {{ .Values.blue.database.storageGB }}
    storage:
      enableVersioning: {{ .Values.blue.storage.enableVersioning }}
      region: {{ .Values.blue.storage.region | quote }}
  compositionSelector:
    matchLabels:
      provider: aws
      type: liferay
  deletionPolicy: {{ .Values.deletionPolicy | quote }}
  green:
    database:
      instanceClass: {{ .Values.green.database.instanceClass | quote }}
      masterUsername: {{ .Values.green.database.masterUsername | quote }}
      region: {{ .Values.green.database.region | quote }}
      storageGB: {{ .Values.green.database.storageGB }}
    storage:
      enableVersioning: {{ .Values.green.storage.enableVersioning }}
      region: {{ .Values.green.storage.region | quote }}
  {{- with .Values.restore.snapshotIdentifier }}
  restore:
    snapshotIdentifier: {{ . | quote }}
  {{- end }}
  search:
    instanceType: {{ .Values.search.instanceType | quote }}
    instanceCount: {{ .Values.search.instanceCount }}
    masterUsername: {{ .Values.search.masterUsername | quote }}
  writeConnectionSecretToRef:
    name: managed-service-details
{{- end -}}