customInitContainers:
  x-liferay-prewipe-hypersonic:
    - containerTemplate: |
        - command:
            - bash
            - -c
            - |
                FLAGFILE=/opt/liferay/data/.hypersonic.prewiped

                if [ ! -e "${FLAGFILE}" ]
                then
                  rm -rf /opt/liferay/data/hypersonic

                  touch "${FLAGFILE}"
                fi
          image: {{ printf "%s:%s" .image.repository (.image.tag | toString) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          name: liferay-prewipe-hypersonic
          volumeMounts:
            - mountPath: /opt
              name: liferay-persistent-volume
image:
  tag: 2025.q1.20-lts
ingress:
  className: "nginx"
  enabled: true
  rules:
  - http:
      paths:
      - backend:
          service:
            name: liferay-default
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
portalProperties: |
  web.server.forwarded.host.enabled=true
  web.server.forwarded.port.enabled=true
  web.server.forwarded.protocol.enabled=true
  web.server.forwarded.for.header=X-Forwarded-For
resources:
  limits:
    cpu: 4000m
    memory: 12Gi
  requests:
    cpu: 2000m
    memory: 4Gi
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  type: LoadBalancer
  volumeClaimTemplates:
  - metadata:
    name: liferay-persistent-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
